### ISSUE TITLE
Unable to collect info

### ISSUE THREAD

**Issue by Eterna1Link** [p0ody/ff2ebook#93]
During download, it is unable to collect info preventing download from fanfiction.net

![image](https://user-images.githubusercontent.com/112227307/229297050-49e075d3-c985-4242-95ea-c83beaaaf31a.png)

**Comment by tetra59** [comment]
I don’t know if this was opened yesterday or a week ago but I have this problem too. I used an alternate site so it’s not a big thing to fix in a hurry, not that there ever is. Just wanted to say that it’s a current issue for today and not one that has been resolved but the issue wasn’t set to close. Happy Easter.

**Comment by MikePrime42** [comment]
![image](https://github.com/p0ody/ff2ebook/assets/114890537/4f8d2e10-7d4d-4e20-96ca-8ab56fd4b143)

Still happening, unless I'm just being clueless about something.

**Comment by tetra59** [comment]
Until they have time to reboot the servers you can try fichub. It’s up and working but if it’s a new chapter then you’ll have to wait a day or so.

**Comment by AstronemaFanKO-35** [comment]
Looks like it's still down

**Comment by p0ody** [comment]
I'll be honest, a while back cloudflare changed again and i tried to get it working but couldn't, so at this point i pretty much gave up.

Im thinking of setting a download with the whole archive and abandon this project.  I dont have the time nor the will to keep trying to keep it working.
